### ISSUE TITLE
Agent Launch Fails on MS Windows

### ISSUE THREAD

**Issue by nikb0yd** [jrh3k5/flume-agent-maven-plugin#12]
With Flume 1.7.0, we get the ability to launch a Flume agent via shell command: **flume-ng.cmd** on Windows, which in turn invokes a PowerShell script: **flume-ng.ps1**. The existing agent launch from the maven plugin fails: **flume-ng**.

Please update the agent plugin to support Flume 1.7.0, and then also detect the OS platform, select the proper launch command, and thereby support launching the agent on Unix, Mac, and Windows systems.

**Comment by jrh3k5** [comment]
Hey - sorry for taking so long to getting around to this. Out of curiosity, do you need this to remain a Java 6 project - more directly, would this feature be unavailable to you if I bumped this up to be compiled by Java 8? My reason for asking is I traffic solely in Java 8 these days, and, if I can dodge installing another JDK, I'd like to. :) But if doing so makes this feature unavailable to you, then I shan't do that.

**Comment by nikb0yd** [comment]
Java 8 is fine for this. We still use Java 7 but need to get off that soon, as it's also at end of life. This issue is very low priority for us, really a "nice to have", as we run our Java stuff on Ubuntu and that works fine. So, this was really just to let you know that some folks may be using Windows. I rarely use Windows for development, but it sometimes comes in handy to check that things work there too.

**Comment by jrh3k5** [comment]
Cool. Thank you!

**Comment by jrh3k5** [comment]
I've got this working on Windows - the release process for Sonatype's OSS hosting has changed since I last used it, so I'll need to tackle that sometime later this week. In the meantime, feel free to pull down what's in master and give it a spin in case I've missed anything glaringly obvious.

**Comment by jrh3k5** [comment]
And, at long last, this is available! Version 3.0.1 of the plugin is now available in Maven central repository with support for launching the agent on Windows. Please take note of issue #19 - the ProcessBuilder, it seems, is deficient on Windows when it comes to killing the processes.
